### ISSUE TITLE
General: Qualitative colormap

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-components#127]
Based on Tol's muted colormap, we propose to use the following 8 colors in order as the qualitative colormap:

rgb(136,34,85)
rgb(136,204,238)
rgb(153,153,51)
rgb(51,34,136)
rgb(68,170,153)
rgb(221,204,119)
rgb(204,102,119)
rgb(17,119,51)

**Comment by asizemore** [comment]
Open question: What should we do if there is no overlay var? 

Options (from Danielle):
1. Use the first color in the tol palette
2. Use the same color as the subset tab
3. Use a color from the site palette
4. Use black
5. Something else?

**Comment by dmfalke** [comment]
> Open question: What should we do if there is no overlay var?

I think the decision was to use the first color in the palette.

**Comment by dmfalke** [comment]
I think we will need to allow for colors to be specified when configuring a plot. This will support use cases where we want to use the same color for values across different plots. My suggestion is that we abstract this by referring to colors by their index number in the palette array. This will allow us to simply have a reference array of values, and we can use the index of that array to specify a palette color.

**Comment by bobular** [comment]
Prelim task: find out what plotly does with empty traces.  So if three traces are normally coloured red,green,blue, and you provide, trace1,emptytrace,trace3, do they still get coloured red and blue (not red,green)

**Comment by d-callan** [comment]
rgb(221,221,221) is the compatible gray, needed for 'No data' values in strata vars. in scatter, i think we also want to use an X marker for 'No data' values to ensure ada compliance if we start using gradient scales there.

**Comment by dmfalke** [comment]
I wonder if we want to have an explicit noData property for our various
plots. I think this will make it easier to ensure consistency, both in
colors and markers. If we go this way, the gray should not be included as a
part of the colorway we pass to plotly.

**Comment by aaronwlsong** [comment]
**QA checking**
Referred  ticket #187, checked all applied plots. On QA website, without overlay variable, the color is the first one: rgb(136,34,85). 

Scatter
<img width="1552" alt="WeChat8062ca86348cfb16558749addac39da8" src="https://user-images.githubusercontent.com/61077845/130123895-4b14f40f-ed4e-41eb-af9f-17abf2af7e8d.png">
 
Histogram
![image](https://user-images.githubusercontent.com/61077845/130124083-4756a05f-4d0a-40bb-8e2b-3c9c7a719cab.png)

Barplot
![image](https://user-images.githubusercontent.com/61077845/130124165-d0043415-a254-4ab8-9e7d-8aefd9e32d7d.png)

Boxplot
![image](https://user-images.githubusercontent.com/61077845/130124290-2a53b0f7-3465-4e08-9203-df297534359f.png)
