### ISSUE TITLE
Fix (broken in FF) and/or disable up/down arrows from number inputs

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-components#132]
The up/down arrows in number fields aren't working in my Firefox (fine in Chrome).

It's possible that we won't want these in the EDA, but might want them in other contexts.

Seems like there's not Material UI prop for this (because it's a browser thing?)

CSS solution seems reasonable:
https://stackoverflow.com/questions/65200093/removing-the-up-and-down-arrows-in-textfield-of-material-ui

Our NumberInput component should have a prop to control this

**Comment by dmfalke** [comment]
I tested in FF with https://veupathdb.github.io/web-components/?path=/story/widgets-number-input--no-bounds, and the up/down arrows work for me. I'm using v90.0 on Linux.

**Comment by bobular** [comment]
Been working for me too now, for many weeks.  Closing, won't fix.
