### ISSUE TITLE
Mouse-over highlighting of a very busy scatterplot is confusing/unhelpful

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-components#137]
Perhaps @moontrip could take a look at this non-urgently.

For example in a GEMS->Information of process->Anthropometry-> Weight vs height scatterplot, there are thousands of points and mouse-over behaviour seems to be tied to the x-axis coordinate, not the x,y position.  With so many points, you can't always highlight the one you want.

Maybe we disable it or change the behaviour?  Needs discussion.

**Comment by bobular** [comment]
Not sure what really needs discussion.  The trivial fix seems good for now.

**Comment by danicahelb** [comment]
@nkittur-uga assigning to you to QA

**Comment by nkittur-uga** [comment]
Tested GEMS1 ->Weight vs height scatterplot and mouse-over now correctly indicates the x,y position. Also tested the mouse-over in PRISM ICEMR ->Age vs Temperature scatterplot and it also correctly indicates the x,y position. 

QA is complete and ticket can be closed.
