### ISSUE TITLE
Scatter plot: Ensure lines are stacked above dots

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-components#160]
I'm not sure what is involved here, but when the dots are dense, it can be hard to see the lines. It would be nice if we could do something to ensure they are more visible. I don't have an example, but will look for one.

**Comment by moontrip** [comment]
@dmfalke I saw David's slack message regarding this. Well those lines are buried anyway with the presence of markers, especially with overlay variable, e.g., country, that are usually have dense data around starting points. Possible solutions off the top of my head are: a) using legend click to hide markers (user's control); b) reduce opacity for markers; c) without changing backend, add more plot options (from frontend) to offer more options, like raw, smoothed mean, smoothed mean with raw, best fit line, and best fit line with raw; d) a plot control to change marker size (?) - like opacity slider

**Comment by moontrip** [comment]
reducing the default marker size may help in most cases. But there may be possibly million data points, which may still be too dense to distinguish lines from markers even with small marker size. Actually I changed marker style not to fill in order to alleviate the issue, but still data with overlay variable hides some of them.

**Comment by dmfalke** [comment]
@moontrip thanks for the comments. I was wondering if the ordering of the plotly traces have an impact on stacking order. I also wonder if we can add a shadow to the lines? That might help give them more definition.

**Comment by moontrip** [comment]
@dmfalke well I don't think stacking order matters too much, but it is more like there are too many data points, even if we are handling thousands of data points only. Honestly, I don't know if it is possible to add a shadow to the lines but I doubt if it helps as those shadows are also buried to other markers/lines. 

For example, here are two screenshots of best fit line with raw: the first one is full plot, and the other one is disabling markers via legend clicks. They show that markers hide lines. Note that each data is less than 4000 data points only, so if it goes over millions, or even over 10,000 level, then there would be not much choice to distinguish lines from markers around dense area.

![scatter1](https://user-images.githubusercontent.com/12802305/123140618-7ebb1380-d425-11eb-91c3-b43a76e01d84.png)

![scatter2](https://user-images.githubusercontent.com/12802305/123140736-a4e0b380-d425-11eb-949d-7501fb3b31d2.png)

**Comment by dmfalke** [comment]
In that first screen shot, it looks to me like the lines are behind the points. I think we should investigate if we can force the lines to be in front of the points. Additionally, if we can add some minimal shadow to the lines, that would also be helpful.

**Comment by moontrip** [comment]
I doubt if there is a way to force lines on top of markers natively (can't find it via some searches), because the line with markers is a single option, `mode: lines+markers`. Perhaps shadow may not help either as it would be overlapped with other lines too.

I tried to use small marker size, and it is better than larger size, but still think more realistic solution is to separate lines and markers in plot

![scatter3](https://user-images.githubusercontent.com/12802305/123147459-11ab7c00-d42d-11eb-9a68-11d883353947.png)

**Comment by dmfalke** [comment]
That definitely helps a lot. I agree that we will also need to allow the user to easily turn off the raw data for all values. We'll need to discuss further to decide what the final implementation will be.

**Comment by dmfalke** [comment]
@moontrip I'm confused by something. Aren't the best fit line and the scatter plot points using different traces?

**Comment by moontrip** [comment]
Yeah I agree with your thought. 
Ah... my bad, you are right. It utilizes different traces: I was confused myself haha :( as trying to say that each stratified data (via overlay variable) is a sort of a group plot having marker and line plots

**Comment by dmfalke** [comment]
I see. My hunch is that traces are stacked based on their position in the array. E.g., the last item in the array will be on the top of the stack. I really think it would be worth trying to sort the traces so that all raw data traces come before the line traces.

**Comment by moontrip** [comment]
Thank you for sharing your thought. But this may be a good example as sorting the trace may not work. In this simple case, it  draws marker at first and then (best fit) line in the end. You can see that the line around the dense area (e.g., x: 0 to 20) is still buried with markers...

![scatter4](https://user-images.githubusercontent.com/12802305/123157766-f2b2e700-d438-11eb-8ab2-9464973218e8.png)

**Comment by dmfalke** [comment]
Yes, I agree that the line gets lost in the dense areas. But in the first picture you posted, there are lines of other colors that are completely covered up by the raw points. If they were on top of the points, they would be visible, since they are different colors than  the sense points.

I'm not arguing that this will solve all cases, but it does lessen the chance of a line being completely obscured.

**Comment by moontrip** [comment]
I got your point and it may alleviate some cases, except the last line that would still be buried.
At this stage, I am not quite sure if lines can be easily on top of markers (they are made of SVGs) and it is worth doing, because it seems to be a daunting task... 🤔

**Comment by moontrip** [comment]
Based on our discussions and an example plot that David showed at slack channel, I think that the current marker size is too large and it is better to be reduced. Following the plot (image attached), I have reduced the marker size (from size: 12 to 6) that is close to the size at the image: a bit larger than previous one (size: 4). This will indirectly lessen the issue as well. Personally I like this size better than before as it is more clear to see their x-axis values/distributions 😊 What do you think?

![image (14)](https://user-images.githubusercontent.com/12802305/123169378-390f4280-d447-11eb-8e64-87e43c7b1963.png)

![scatter5](https://user-images.githubusercontent.com/12802305/123169409-43c9d780-d447-11eb-8008-d4f7e174d140.png)

**Comment by dmfalke** [comment]
I like this smaller size for the markers. I think that's a worthwhile change.

**Comment by dmfalke** [comment]
@moontrip I played with this a little bit, and I was able to get lines to appear in front of points by making two changes:

1. Sort raw traces before line traces.
2. Use `type=scattergl` for all traces.

This is the result:
![image](https://user-images.githubusercontent.com/365139/123174050-85f61780-d44d-11eb-8610-7079ff9784bb.png)

The legend ordering changes, but maybe it's okay.

**Comment by moontrip** [comment]
@dmfalke It is very exciting plot 👍 I didn't think it would work like that: had a plan to test but worked for others. One question is whether the `type: scattergl` is mandatory to be the lines in front of markers? 

It would be great if you can share the sort part as well :)

**Comment by moontrip** [comment]
@dmfalke yeah I could get similar plot like your screenshot following your suggestions. 👍 Also I realized that `type: scattergl` is a must to make lines in front of markers (following the order of traces). One disadvantage in this case is that scattergl does not support spline option, so some smoothed mean and confidence interval plots may not be that smooth.
