### ISSUE TITLE
Visualizations: check size of white outline on RXC plots

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/web-components#180]
Danielle noted that if you look at GEMS1 and make an RxC plot with country on x and floor material on y, it seems like the breaks between boxes differ in size. In particular, if you look at the top edge of the plot, the bars seem to end at different heights. 

Need to have Connor confirm whether it's drawing white rectangles around the colored boxes, and if the width of the lines varies based on the size of the inner box. If so, we need to change this to use a standard, maybe thinner, line width

**Comment by chowington** [comment]
It is drawing white rectangles around the boxes. Where these outlines seem to differ in width, it's mostly the result of tiny boxes there that are too small for their color to appear. Plotly seems to prioritize the outline over the box when drawing tiny boxes. I can try a smaller outline width and see if that makes things better.

**Comment by chowington** [comment]
For instance, on the "Mali" column, the thicker white outline near the bottom of the column actually contains a bunch of tiny boxes within it:

![image](https://user-images.githubusercontent.com/12377649/130137396-bb8d0b82-f8bf-43e9-8b24-404250242f05.png)

**Comment by chowington** [comment]
The border width is currently 2px; the following is what is looks like at 1px:


(RxC) Floor material vs Country

![image](https://user-images.githubusercontent.com/12377649/130141536-bfe80031-b478-44fe-90a4-0fb431a62f3b.png)

(2x2) Given stored water for drinking vs Case or control participant

![image](https://user-images.githubusercontent.com/12377649/130141815-d12a6a43-7a42-4587-96a1-52057a4ab7c3.png)

**Comment by SheenaTomko** [comment]
I think 1 px looks better. Is it possible to even try 0.5 px (or are pixels integer only)?
@d-callan any other thoughts?

**Comment by chowington** [comment]
@SheenaTomko Technically pixels are supposed to be integers as they represent literal pixels on your computer screen, however you can do non integer values and less than 1 even. I wouldn't recommend it though because the behavior is pretty inconsistent though, as shown here at 0.5px:

![image](https://user-images.githubusercontent.com/12377649/130659924-b8cc3f4f-5adc-4508-8ef0-e511ab0fdee2.png)

**Comment by SheenaTomko** [comment]
Yeah that's not good. I guess lets go with 1 px unless @d-callan or others have other ideas

**Comment by chowington** [comment]
Actually, 1px seems to be a bit odd too sometimes. Here some of the columns don't have borders between them. Is that a concern?

![image](https://user-images.githubusercontent.com/12377649/130691054-ac1ce97f-7d31-4f7a-a600-f94194921eb1.png)

**Comment by chowington** [comment]
Whoops--nevermind, I made a mistake. That image is with 0.5px. 1px looks fine. My bad!

**Comment by SheenaTomko** [comment]
1 px looks good.
