### ISSUE TITLE
Visualizations: Move x-axis labels on RxC and 2x2 plots

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/web-components#181]
Move X-axis labels below the axis and don’t show the % on bottom. Also, remove the % and count from the end of the labels.

**Comment by chowington** [comment]
What's the reason for removing the raw counts and percentages from the x-axis values at the bottom? To me it seems like useful information that can't be gotten anywhere else from the plot or table view (no percentages). I know that's not how the original Shiny plot is or probably how contingency tables are generally. Maybe we could make it an option to turn them on via the plot controls at the bottom of the page (visible on other visualizations)? I have the same feeling about the 0-100% x-axis scale. Thoughts?

**Comment by SheenaTomko** [comment]
Part of the reason to remove the scale from the x-axis is just so it doesn't get in the way of the value labels. I would be ok with an option to turn it on via plot controls at the bottom.

For the x-axis value labels themselves, I think it's a little confusing to have those counts and percentages for that variable when we don't do the same for y-axis values. It also makes the labels longer and harder to read. In theory, we could add that information to the y-axis labels as well, but I think it might be overkill. 

@d-callan can add her thoughts

**Comment by d-callan** [comment]
to me, keeping the treatment of the axes as consistent with each other as possible, and with the general expectations for a mosaic plot is important. mosaic plots usually have categorical axes labels, and not a scale representing the percentage. a user familiar w mosaic plots will potentially be confused by this, and one who isnt shouldnt be bothered either way. i tend to think we shouldnt offer it, even as an option. as for the % in the labels, i agree w sheena they feel a bit like theyre cluttering the space, but would be fine w offering those as an option.

**Comment by chowington** [comment]
Thanks for your comments both! Since there doesn't seem to be consensus or a big drive to keep these extra elements, I'll just go ahead and remove them both as requested at first for now.

**Comment by SheenaTomko** [comment]
Looks good thanks. Going to open a second ticket to add the variable name as an axis label
