### ISSUE TITLE
Visualizations: Make smoothed mean/best fit lines darker than points in scatter plots

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/web-components#183]
Scatter plot trend lines get lost in the points. Suggestion - color a slightly darker shade than the points and ensure it is on top. Ex: GEMS, x-axis: age, y-axis: weight

**Comment by moontrip** [comment]
@SheenaTomko Perhaps this work would need to be done after color palette is implemented for plots.
That being said, I have a couple of questions for clarification.

a) should the plot "95% confidence interval" at smoothed mean be darker like the mean line or just leave it as is ? 
b) I think that there are two possible approaches in this regard: i) change opacity, e.g., making marker's opacity lower than line; ii) change  RGB value (color) for lines to be darker. Which one do you have in mind?

**Comment by SheenaTomko** [comment]
@asizemore I made this ticket based on an item you'd added to the spreadsheet. Maybe you can provide DK more feedback. My guess is for a) that we leave the 95% confidence interval alone and just change the mean line. For b) I'm ok with either option

**Comment by moontrip** [comment]
@SheenaTomko Thank you for your clarification 👍 I will check this out after the color palette work is done

**Comment by asizemore** [comment]
@moontrip good questions. This turned into a harder problem that I initially expected, as these things tend to go :)
I'll make some examples to discuss and get back to you!

**Comment by asizemore** [comment]
After a discussion on the data-viz team (see slack for more details), we decided it would be easiest for this phase to simply make the trend lines and confidence intervals slightly darker. Below I'll list the color pairs, with the current color (to be used for markers) on the left in `[]` and the corresponding slightly darker color (for trendlines and confidence intervals) on the right in `()`. We decided not to change any of the opacity settings for these traces for phase 1.

RGB
[136, 34, 85]     (115, 28, 72)
[136, 204, 238]     (113, 194, 234)
[153, 153, 51]      (133, 133, 44)
[51, 34, 136]       (43, 28, 115)
[68, 170, 153]      (60, 151, 136)
[221, 204, 119]      (215, 196, 98)
[204, 102, 119]       (197, 82, 102)
[17, 119, 51]      (13, 96, 41)

**Comment by moontrip** [comment]
Thank you for your information. It would be very helpful to work with 👍

**Comment by moontrip** [comment]
@asizemore I have made [a PR](https://github.com/VEuPathDB/web-eda/pull/355) to address this issue. One issue I have is that although your darker color palette was correctly applied, it is not that distinguishable from the original color palette visually. Perhaps new dark colors are not that much darker than  original one ? Please see my comment and screenshot here, https://github.com/VEuPathDB/web-eda/pull/355#issue-723463003

**Comment by asizemore** [comment]
Hey @moontrip the implementation looks great! You're right, the darker colors are not that much darker. We had to balance darkening all the colors in the original color palette with trying to keep all the colors accessible. It's also important that the darker color is still close enough to the original color that the user pairs them together. In the most ideal scenario, the user wouldn't be able to tell the difference between the pair of darker and lighter colors when they are near but not touching, but could see the darker color stand out when it is atop the lighter color (see picture). But I digress :)
<img width="1284" alt="Screen Shot 2021-09-01 at 9 34 38 AM" src="https://user-images.githubusercontent.com/11710234/131680997-2505b1a3-622d-4c6d-9dfc-ae9814cb5504.png">

All that is to say your concern is a good one but I think right now the above is about as dark as we can go without diminishing accessibility too much.

**Comment by moontrip** [comment]
> Hey @moontrip the implementation looks great! You're right, the darker colors are not that much darker. We had to balance darkening all the colors in the original color palette with trying to keep all the colors accessible. It's also important that the darker color is still close enough to the original color that the user pairs them together. In the most ideal scenario, the user wouldn't be able to tell the difference between the pair of darker and lighter colors when they are near but not touching, but could see the darker color stand out when it is atop the lighter color (see picture). But I digress :)
> <img alt="Screen Shot 2021-09-01 at 9 34 38 AM" width="1284" src="https://user-images.githubusercontent.com/11710234/131680997-2505b1a3-622d-4c6d-9dfc-ae9814cb5504.png">
> 
> All that is to say your concern is a good one but I think right now the above is about as dark as we can go without diminishing accessibility too much.

Hi @asizemore Thank you for your detailed explanation 👍 Yes I also checked RGB values between original and darker ones and realized the latter is certainly darker than the former like your example Scatter plot has just thin lines (and shaded ones), unlike thick bars like your example 😃

**Comment by SheenaTomko** [comment]
color intensity looks good
