### ISSUE TITLE
Visualization: handling long axis tick label with ellipsis and tooltip for Mosaic plot

### ISSUE THREAD

**Issue by moontrip** [VEuPathDB/web-components#214]
This work is a kind of an extension of previous task, [long axis tick labels for barplot and boxplot](https://github.com/VEuPathDB/web-eda/issues/328), which would apply to Mosaic plot.

**Comment by nkittur-uga** [comment]
Tested in GEMS1 and this is not working.
<img width="1440" alt="Screen Shot 2021-09-24 at 10 12 25 AM" src="https://user-images.githubusercontent.com/67710160/134689079-bc142217-696e-474f-a35c-a5ac65135e78.png">

**Comment by moontrip** [comment]
@nkittur-uga Thank you for your tests. Actually this ticket is for handling long independent axis (X-axis) tick label, not long axis title. In this example, axis tick label means "Case" and "Control", while axis title you probably thought is Y-axis title "All lab forms complete..."

Certainly I noticed the cutoff of Y-axis title and there exist ticket for this, which you have made before 😃 ([here](https://github.com/VEuPathDB/web-eda/issues/395)). If you think the long axis title should also be addressed as fast as possible, please let me know then I will work for that possibly early next week.

By the way, I have one question. I tested with https://qa.clinepidb.org/ for your usecase (the screenshot you showed above) but it threw 500 server error now. Is the web address correct to test qa site ?

**Comment by nkittur-uga** [comment]
Hi @moontrip sorry for QAing the wrong thing! Let me QA the right thing (X axis) and comment back.

The Y axis thing should ideally be addressed for Phase 1 but not a huge deal if it is put off until Phase 2. In my opinion.

This is the qa site
https://qa.restricted.clinepidb.org/ce.restricted.qa/app/

**Comment by moontrip** [comment]
@nkittur-uga No problem at all! 👍 Please also take a look at [my PR](https://github.com/VEuPathDB/web-components/pull/213) that has some screenshots FYI (Bob also made one for his test): I usually made screenshots after resolving an issue, which may be helpful for you in some cases 😃 

And thank you for the site link! I didn't know its presence.

**Comment by nkittur-uga** [comment]
@moontrip what I'm finding is that the graph gets wider as the X axis label gets longer. It is not a fixed width with ellipsis if the label is longer than that fixed width.

**Comment by moontrip** [comment]
@nkittur-uga Thank you for your observation. Actually there is no specific way to use fixed width of pure plot/figure (plots without tick, title, legend, etc.) in Plotly as it is automatically computed based on other parts like legend text length, X-axis tick label length, etc. Thus, from my understanding, the only way to minimize the issue is to reduce those lengths so that the pure plot/figure is shown reasonably, not like below screenshot before using this approach - this also shows how plotly handles the pure plot/figure. You can also see some screenshots in there too 😃 

https://github.com/VEuPathDB/web-eda/issues/328#issue-976539599

**Comment by nkittur-uga** [comment]
Long labels on X axis look OK. QA is complete.
