### ISSUE TITLE
Faceting: Fully implement FacetedPlot component

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-components#240]
Subtask to VEuPathDB/web-eda#635 

Continues work on https://github.com/VEuPathDB/web-components/pull/162

- [ ] decide on subplot size
- [ ] make simple story for each plot type (PiePlot is done)
- [ ] minimise margins within subplots (
- [ ] minimise spacing between subplots (and get rid of temporary dotted outline)
- [ ] render entire faceted plot in the drop-shadow border (not each plot)
- [ ] fixed width and simple browser-based horizontal scroll bar
- [ ] titles (showing facet.value) may need ellipsis support for long values

Optional for build 55
- [ ] click-on-plot to an enlarged modal
- [ ] "No data" facet styled differently (perhaps the title has a grey background)

**Comment by dmfalke** [comment]
Most of this work is actually being done in web-eda. When we have some more time, we will move much of this work to web-components, as plot-specific variants of `FacetedPlot`.

**Comment by nkittur-uga** [comment]
Faceted plots look good.
