### ISSUE TITLE
Contingency table needs comma-separated thousands number format

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-components#255]
Should be trivial, doing it now...

Previously:

![image](https://user-images.githubusercontent.com/308639/141688703-1f8d5967-7f1a-4d89-9e68-7f45ae58c656.png)

**Comment by sweverschulman** [comment]
currently on qa.restricted and qa there is no comma in the thousands place for the values in the table. 
<img width="748" alt="Screen Shot 2021-11-15 at 11 13 38 AM" src="https://user-images.githubusercontent.com/62298921/141816563-8bee8e51-2302-4708-a16a-9184561bee9b.png">

**Comment by bobular** [comment]
This is odd.
https://github.com/VEuPathDB/web-eda/issues/701
was resolved with pull 704 which included an [upgrade of web-components](https://github.com/VEuPathDB/web-eda/pull/704/commits/e5fcc12c6799ffcd10aa6fa9cd9070915f106258)
which is in **Ready for testing** and so I assume was rolled out to QA

Sorry, paging Dr @dmfalke !

**Comment by moontrip** [comment]
@bobular as asked Dave at slack, my custom legend works for scatter plot were not reflected correctly.

**Comment by bobular** [comment]
Working now on QA
![image](https://user-images.githubusercontent.com/308639/142197810-a8cfdfe9-af5e-482b-8bda-99741e9a827b.png)

I'll move this to Completed

**Comment by dmfalke** [comment]
Sorry I missed your comment @bobular!
