### ISSUE TITLE
Mosaic plot: Make ticks vertical for consistent plot dimensions

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-components#257]

**Comment by danicahelb** [comment]
more information on the issue can be found in https://github.com/VEuPathDB/EdaNewIssues/issues/84, which is a duplicate ticket that I have closed

**Comment by aaronwlsong** [comment]
It seems that the issue has been solved, closing ticket. 

![image](https://user-images.githubusercontent.com/61077845/142227711-bde4fdf4-eaca-4269-ad59-e23b645022db.png)

![image](https://user-images.githubusercontent.com/61077845/142227856-e2b79f9c-7b62-4967-80db-698ef4f967d9.png)
