### ISSUE TITLE
Faceting: individual `FacetedPlot` types

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-components#259]
This is a follow-up to #240, which lists tasks for `FacetedPlot`.

- [x] make `FacetedPlot` components for each plot type (e.g., `FacetedBarPlot`)
- [x] make simple story for each plot type (PiePlot is done)
- [x] click-on-plot to an enlarged modal
~~"No data" facet styled differently (perhaps the title has a grey background)~~ Fixed in https://github.com/VEuPathDB/web-components/pull/262

**Comment by chowington** [comment]
Striking out the third task above because it was done in https://github.com/VEuPathDB/web-components/pull/262

**Comment by dmfalke** [comment]
@chowington I must have authored this issue in haste. It is missing a crucial component, which is to make a `FacetedPlot` component for each of the plot types we provide. Ideally, they should use styling similar to what we are doing in visualizations in web-eda. I will update the description to reflect this. Sorry for the confusion. The stories do look great!

**Comment by chowington** [comment]
@dmfalke I started work on the individual plot components but I don't have a great idea of how to integrate them into our existing structure, particularly with `FacetedPlot`. I just worked on the `FacetedBarplot` as a test run and pushed it to a different branch than this one: https://github.com/VEuPathDB/web-components/tree/individual-facetedplot-components. It's not currently functional, but you can see what I'm attempting to do. Let me know what your thoughts are.

**Comment by chowington** [comment]
Bumping up to high cost due to extra core-components modal work for good housekeeping

**Comment by nkittur-uga** [comment]
Dave advised that the primary ux change is the ability to click on a facet to see an enlarged plot. I tested this and it works. Passes QA.
