### ISSUE TITLE
Birds eye view mouseover no longer shows the "bracket" (----|) counts

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-components#263]
It should show three or four numbers, not just two.

This is probably a result of the plotly upgrade that we missed.

![image](https://user-images.githubusercontent.com/308639/142234017-b4b9884f-9c3e-497d-8c40-ca03ed58e41a.png)

**Comment by nkittur-uga** [comment]
Mouseover now shows all counts. Passes QA.
<img width="1137" alt="Screen Shot 2021-11-19 at 9 35 50 AM" src="https://user-images.githubusercontent.com/67710160/142640150-62129890-52ca-4e3b-a374-d9232077680a.png">
