### ISSUE TITLE
Mosaic: Y-axis labels container sometimes overflows plot height

### ISSUE THREAD

**Issue by chowington** [VEuPathDB/web-components#265]
The mosaic y-axis labels (it's not a legend *shhh*) container overflows the height of the plot and gets a scrollbar if the x-axis labels are too long. This is because the y-axis labels container height is calculated based on the assumed minimum height of the plot, which has become smaller now that the x-axis labels are vertical rather than slanted.

**Comment by chowington** [comment]
See this comment for a test case: https://github.com/VEuPathDB/web-components/pull/266#pullrequestreview-809860627

**Comment by chowington** [comment]
Image of y-axis labels overflowing their container---notice scroll bar to their right. This is on GEMS1.

![image](https://user-images.githubusercontent.com/12377649/142512847-57a66050-136b-467f-9ab5-695ceba5c5e9.png)

**Comment by aaronwlsong** [comment]
It looks good now, closing ticket.

In GEMS1:

![image](https://user-images.githubusercontent.com/61077845/142640546-d9f6d5d5-ace4-48f1-818a-40975a1c861f.png)

In other studies: 
![image](https://user-images.githubusercontent.com/61077845/142640958-ff9b3ebc-a9c0-4283-8e89-16e036abe0c5.png)
