### ISSUE TITLE
New custom legend mouse pointer feedback is confusing

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-components#271]
Tested with FF in Linux

When mousing over the text in the legend, the mouse pointer becomes a finger, suggesting clicking will do something, but it doesn't.

Pointer behaviour when mousing-over the coloured square, circle or lines is as expected
Same for the checkboxes.

But the text is disconcerting.

Perhaps the text should be clickable too (but not the legend title).

And maybe double click should emulate what Plotly does?  (very optional - get feedback from outreach first!)

**Comment by moontrip** [comment]
Thank you for your info. Well if you want to have click label, then we probably need to use conventional input checkbox, not material UI one. And sure you can make it draft PR for me 👍

**Comment by bobular** [comment]
Oh, do Material UI checkboxes not have click-labels?  That seems like retrograde evolution...

**Comment by moontrip** [comment]
Actually material UI's checkbox support clicking label text, if the label is also made of material UI. However, one big issue to use material UI's label was that it only accepts string, thus there was no way to have markers in front of material UI's label. 

For this reason, the current legend label is actually using HTML <Label> for flexibility, thus it is beyond material UI

**Comment by bobular** [comment]
Oh I see - well I'm sure we can make them clickable some other way, but not now.  Have a nice weekend!  Thanks for all your hard work!

**Comment by moontrip** [comment]
Thank you for your great efforts too! 👍 👍  Have a great weekend too!

**Comment by moontrip** [comment]
There are three things that may need to be addressed in this ticket concerning custom legend

a) changing checkbox color into grayish - discussed at [#86](https://github.com/VEuPathDB/EdaNewIssues/issues/86)
b) considering scrollbar when the number of legend list is large
c) making legend label clickable to select/unselect checkbox

**Comment by nkittur-uga** [comment]
Confirmed that custom legend checkbox is grey, and legend label is clickable to select/unselect checkbox. Passes QA.
