### ISSUE TITLE
Map component: add a `flyTo` prop that performs a one-off recenter and zoom to fit all data

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-components#294]
This is something that was a bit tricky/unreliable in MapVEu 1.0

I think this is something that should be "component-side" rather than application-side, but am open to suggestions!

Here is the behaviour/spec I think we need:

- the following behaviour happens only once per lifetime of the map component (presumably requires component state to keep track of this)
- the component (or SemanticMarkers component) calculates the bounding box of all the marker data it is given (it is up to the application to start with a low enough zoom level) and then recenters/zooms to that view
- the above will probably be achieved with `map.fitBounds()` as in `BoundsDriftMarker` - hopefully all the viewport/bounds update callbacks will be called as normal
- the desired behaviour in EDA would be that the first map render (from (0,0) zoom=1) would 'flyTo' but the thumbnail and saved visualization configuration would be the flown-to location.  Therefore upon opening a thumbnail in EDA, it would not do any flying.

While doing this please also look into the min zoom level issue pointed out [here](https://github.com/VEuPathDB/web-eda/blob/main/src/lib/core/components/visualizations/implementations/MapVisualization.tsx#L50). I think the component should zoom out to level 1 if possible.  We just need to check the multiple worlds story is OK.

Hopefully `low cost`, if we find a simple approach!

**Comment by nkittur-uga** [comment]
Passes QA.
