### ISSUE TITLE
Map component needs a prop for the background tile choice

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-components#295]
The background tile selection is currently hardcoded and I guess it can stay this way.

Applications that use this component may want to set (and remember) the background tile choice so we need a mechanism to control this via a prop, not just the leaflet UI element that we currently have.

I guess to keep things simple, the prop can be an arbitrary string.  If the value doesn't match one of the layers, then just revert to default.  There should, of course, also be a callback to communicate any state changes to the outside world.  

There's some EDA-side work here too (including updating the thumbnail generation dependencies).  Give me @bobular a shout when you get started here and I'll make a ticket there too.

**Comment by chowington** [comment]
I can start on this @bobular. Do you envision keeping the leaflet UI picker as well? Would the prop just be for the default tiles or would it fully control the tiles?

**Comment by chowington** [comment]
To QA, first change the map's base layer via the menu at the top right, then minimize the map viz and come back to it. The base layer should still be what you changed it to rather than the default.
