### ISSUE TITLE
Box Plot legend: Mean and median lines should have place in legend

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-components#303]
When we make a boxplot, a user doesn't know for sure if the mean/median is the solid/dashed line.

<img width="181" alt="Screen Shot 2022-02-16 at 5 15 49 PM" src="https://user-images.githubusercontent.com/11710234/154366625-ecc9b9ca-e3e0-4476-a11f-f51c585a0969.png">

Would be very helpful to have this indicated in the legend, or possibly below the plot. I don't think it's necessary to show this info repeated for each color (like we do in scatter with trend lines), instead it's common to just have the stroke type in black so that the user understands it's the stroke type that's giving the information and that it applies to all colors. 

<img width="387" alt="Screen Shot 2022-02-16 at 5 18 24 PM" src="https://user-images.githubusercontent.com/11710234/154366990-6c13282a-0629-47cf-bdce-f308810fd6cc.png">

I guess if we wanted to be really fancy, if there is no overlay the mean/median legend lines would be the same wine color of the boxes, and then if there is an overlay the mean/median legend lines would be black :)

**Comment by moontrip** [comment]
@asizemore Thank you for your detailed description. Perhaps we can consider placing it below custom legend as well - no overlay does not carry legend so it may be placed at the legend location.

**Comment by asizemore** [comment]
@moontrip good idea! I think that would work really well!

**Comment by moontrip** [comment]
@asizemore Here are mock-ups for your suggestions. Are they alright for your intention?

# no overlay (no custom legend) - wine color for lines
![boxplotViz-mean-no-overlay](https://user-images.githubusercontent.com/12802305/155001493-af9ff7e9-bc9a-4650-b3d6-971b2515fa7f.png)

# with overlay (with custom legend) - black colors for lines
![boxplotViz-mean-overlay](https://user-images.githubusercontent.com/12802305/155001551-0b5a592c-5d23-48e5-ade6-4e71396eceda.png)

**Comment by asizemore** [comment]
@moontrip these look great! I'm now curious if we should add the boxplot fences to the legend, too? I asked the dataviz channel about it and will let you know what they say!

**Comment by moontrip** [comment]
@asizemore thank you for your confirmation. Not quite sure how you would distinguish fence from median as both are lines. Also I think that people who use boxplot generally know about fence without explanation ? 😃

**Comment by asizemore** [comment]
> Also I think that people who use boxplot generally know about fence without explanation ?

Haha @moontrip that is exactly my question! Usually people would know about the median as well as the fence without explanation. So it's most important that people see the mean in the legend for sure, but is it helpful to then also see the median and fences? Or is that just extra info? I'm not sure 😄

**Comment by moontrip** [comment]
@asizemore Haha, adding fence explanation seems to be an overkill for me 😄

**Comment by danicahelb** [comment]
in 2/23/2022 data vis meeting, we decided that --instead of adding mean & median to the plot legend -- we will add it to plot documentation. we will create documentation for all visualizations (topic for #eda-user-documentation WG) and decide how best to incorporate this documentation into the site

**Comment by moontrip** [comment]
This is not pursued anymore based on the above comment, so closing
