### ISSUE TITLE
Bug: change truncation indicator bar on subsetting histograms from grey to yellow

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-components#305]
I'm looking at the WASH-b Bangladesh study, variable "Household year". I have not applied any filters to the dataset. When I zoom in the x-axis so that the range is from 2000-2015, I get a grey bar (the "All households" color) at ~2000

If I change the x-axis zoom to 1980-2015, then the grey bar moves to ~1980

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/25450900/154095917-50f879be-e90d-4332-ac52-f9a2029033de.png">

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/25450900/154096013-cd6b43e4-67f9-4d2f-8956-1df8e0960bd0.png">

**Comment by moontrip** [comment]
This is addressed for both color and message. Screenshot is attached here.
![truncation-medium-yellow](https://user-images.githubusercontent.com/12802305/155439655-68341071-1d4e-4a2a-8339-b13f796b2836.png)

**Comment by bobular** [comment]
Not worth redeploying but I'd suggest removing the word "medium" from the blue warning text next time we have a PR in these files. @moontrip

**Comment by bobular** [comment]
Just a quick comment on the hatched shading/patterning.

I think we all agree it would look good, but it doesn't come for free in [Plotly shapes](https://plotly.com/javascript/shapes/).

However, we could draw the diagonal lines or shapes ourselves (either as lines or SVG paths).  It would be a low-medium cost task IMO.

**Comment by moontrip** [comment]
@bobular I agree with you: I was debating it myself too 👍 As Dave already deployed this PR to qa, not quite sure if I have a chance to change it. Will ask him if he has a plan to deploy something to qa: if not, then will change it later.

As for the shape, actually there is a possibility for that, but diagonal shaping with SVG is quite tricky. I once tried to check the case before, but concluded that it is not simple task under plotly with several considerations. For example, we first need to set width and height of the SVG correctly for the shape but due to the nature of plotly's dynamic scaling, it is hard to determine them.

**Comment by bobular** [comment]
Thanks for the update, @moontrip - I didn't know there were extra challenges to the SVG approach.

Using the 'line' Plotly shape for the diagonals won't be straightforward either because the ends of the lines won't be flush with the edge of the rectangle. It could look quite ugly.

**Comment by moontrip** [comment]
@bobular yes I agree. It is quite tricky one to deal with overall and am worried we would not earn much benefit as compared to our potential efforts on this. Wish plotly extends their functionality to support some basic patterns for such shapes 😉

**Comment by aaronwlsong** [comment]
It looks good now, closing the ticket.
<img width="1873" alt="Screen Shot 2022-02-24 at 2 30 08 PM" src="https://user-images.githubusercontent.com/61077845/155593982-c2617a57-266a-4494-84b6-970c52ae88e1.png">
<img width="1603" alt="Screen Shot 2022-02-24 at 2 28 24 PM" src="https://user-images.githubusercontent.com/61077845/155593985-c96e70a4-5a29-4275-bd69-cbf5760f482d.png">

**Comment by moontrip** [comment]
Thank you for your tests and reviews @aaronwlsong 👍 Just FYI, we have decided to change the message (blue one) text from medium yellow to (shortly) yellow and I did it but you would not need to review it again, I suppose 😃
