### ISSUE TITLE
adjust y-axis range to properly accommodate smooth mean & CI data

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-components#311]
when the smooth mean line extends past the y-axis range, please extend it to accommodate the line. (note in the example below, when raw data is selected, y-axis ranges from 0 to 15. when smooth mean is selected, the range changes from -40 to 20, but the line still gets cut off)

example from llineup:
<img width="1414" alt="image" src="https://user-images.githubusercontent.com/25450900/156064280-be26e639-deae-4cd1-9732-4a146e85c429.png">

**Comment by danicahelb** [comment]
much better, thanks! 
<img width="451" alt="image" src="https://user-images.githubusercontent.com/25450900/156459279-e1c6f82e-8aa6-494c-8978-9566bdaf069f.png">

**Comment by moontrip** [comment]
Thank you for quick test, @danicahelb 👍
