### ISSUE TITLE
Map: MapVEuMap should show a scale bar

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-components#313]
Like you see bottom right in the legacy map.

![image](https://user-images.githubusercontent.com/308639/156611382-9ef65df9-6483-4880-a37e-f06e023f94f8.png)

Location should probably also be bottom right.  Add a prop to turn on/off.

**Comment by moontrip** [comment]
perhaps I can take this as a part of map upgrade

**Comment by moontrip** [comment]
@bobular make default show the scale ?

**Comment by bobular** [comment]
Sorry for the delay. There have been discussions about *not* showing the scale when the curvature of the Earth is likely to cause issues. Default behaviour might be to show the scale when zoom level > X.  Not sure what X is though!

**Comment by moontrip** [comment]
@bobular thank you for your information! 👍 Then perhaps the best approach is to set a prop, e.g., showScale (boolean), at MapVEuMap component, then pass showScale from a parent component, e.g., MapViz at web-eda, to control its boolean value depending on the zoom level. In this way, we would not need to touch MapVEuMap component anymore (if hardcorded, then we have to change MapVEuMap again depending on X value if one changes it to be another value)
