### ISSUE TITLE
Histogram: right hand coordinate of blue selection area seems to be affected by local time zone for date variables

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-components#322]
In EDA subsetting, if you zoom in to few days of GEMS1 observation date, binning at 1 day, and make a selection, the right hand edge of the blue selection is not quite at the edge of the bin.

![image](https://user-images.githubusercontent.com/308639/157882139-28042090-72ce-483b-934c-bb03361c45c9.png)

It turns out that the right hand edge isn't drawn at 1 millisecond to midnight, but 1 millisecond to 11pm

`x1: "2011-05-02T22:59:59.999Z"`

I am in GMT/UTC timezone, which makes this super-mysterious.

For those on Eastern time, the `x1` coordinate is even more displaced.

Here's the code that is responsible.

https://github.com/VEuPathDB/web-components/blob/9c69105b4948585019738de644ccfd47b7a194c6/src/plots/Histogram.tsx#L297-L300

It may be that `new Date(range.max)` is made in the local time. `range.max` may need 'T00:00:00Z' appending before converting to Date.

While diagnosing/testing it may be necessary to "spoof" different timezones from your browser. Chrome dev tools can do this, as can firefox plugins (not specifically dev-oriented).

**Comment by SheenaTomko** [comment]
<img width="826" alt="Screen Shot 2022-04-11 at 3 10 32 PM" src="https://user-images.githubusercontent.com/54597319/162823992-82fc3b0b-7b10-4d90-a9e6-5d0f88b805f9.png">

This looks good now. Also tested with San Francisco, Tokyo, and a couple other timezones. No issues
