### ISSUE TITLE
Update entity diagram to differentiate 1:1 vs 1:many relationships

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-components#326]
There has been a proposal to update the entity diagram. Arrows should be removed as there is no directionality in relationships. Nodes can be styled to differentiate 1:1 vs 1:many relationships.

Mouse-over text for the edges? May be difficult to universalize accurately…
For example:
- In this study, each Household had one Participant
- In this study, each Household had one or more Household Repeated Measures

<img width="666" alt="image" src="https://user-images.githubusercontent.com/25450900/156658713-947bd475-70f0-4609-9a4a-d9fb3956174f.png">

This proposal needs sign-off from EDA WG before implementing...

**Comment by SheenaTomko** [comment]
This file contains all 1:1 relationships that need to be updated in the database. 

[1_to_1_relationships.csv](https://github.com/VEuPathDB/web-components/files/8496532/1_to_1_relationships.csv)

**Comment by SheenaTomko** [comment]
The lines themselves look good. Ryan changed all to be 1:1 for this release since dd isn't ready for the change. Will have a separate redmine ticket for DD to implement the schema changes and load this 1:many information as part of the workflow

**Comment by danicahelb** [comment]
For b57, we have successfully replaced the arrows with nodes
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/25450900/163886834-20ebef46-0a8c-4bed-9afc-5966b9423134.png">

We are not yet able to differentiate 1:1 vs 1:many relationships with the diagram. Backend work is needed, see: https://redmine.apidb.org/issues/47686
