### ISSUE TITLE
Faceted visualisation 'full screen' modal needs layout fixes, takes up only half of screen height

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-components#339]
Tested in FF and Chrome.
Three things

1. The top edge of the modal border is overwritten by the plot div, making a white break in the top border
2. The plots are only taking up half of the modal
3. Not really a styling thing but I am finding some reliability issues with the mouseOver and onClick behaviour (doesn't always work) - please keep an eye on this and see if you can diagnose while fixing 1&2.  Enlarging faceted plots also seems to make the `Visualize` tab unclickable in some cases. Leaving the browser tab and returning later can magically fix it.

Edit to add: can't reproduce ANY of these on the live site.
Edit to add: 2022-11-09: I CAN reproduce this on the live site. The using-half-the-screen is becoming annoying for me! (@bobular)

![image](https://user-images.githubusercontent.com/308639/162446775-a98e70b4-c6a2-4c19-af7c-5173ddb11e22.png)

**Comment by danicahelb** [comment]
Fullscreen / expanded faceted plots aren't centered in modal is a reproducible issue. See https://github.com/VEuPathDB/web-eda/issues/1217 and https://github.com/VEuPathDB/web-components/issues/373

**Comment by bobular** [comment]
Would like to bump this! Still an issue, developer sites and live site!

**Comment by SAK22** [comment]
Looks good!
