### ISSUE TITLE
Widen viz plot legend to 400px and take care of ellipsis processing too

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-components#344]
With the new layout going out in b57, there is space available to widen the legend to 400px (used by the coverage table and birds eye plot) - with 10px padding I think.

The length threshold for the ellipsis handling may also need changing. Ideally this should be a prop, not hardcoded.

Looks like the code is in PlotLegend.tsx

While there we should see if we can remove some EDA-specific behaviour (from the comment below, at least)
```
            maxHeight: 250, // same height with Scatterplot R-square table
```

**Comment by dmfalke** [comment]
The ellipsis behavior can be controlled via the CSS rule `text-overflow: ellipsis`. This will allow things to be more dynamic and responsive. See https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow.

I think the width should probably be a prop, or controlled by the component rendering this one.

**Comment by bobular** [comment]
True, and I have even used it recently, duh!
I think the character-based truncation was a hangover from the days when we had to hack Plotly's tooltips.

**Comment by bobular** [comment]
While we are at it, I think the "title" of the legend needs some formatting tweaks.
Maybe it just needs to be in bold, or perhaps the spacing is a bit off.  Certainly for this very short "Sex" one below it doesn't look quite right.

![image](https://user-images.githubusercontent.com/308639/163481335-f2876a6b-3f9a-42cf-9a7b-552082d3f8bd.png)

**Comment by SheenaTomko** [comment]
Looks good. Legend box is now wider by default and the variable name within it is bolded
