### ISSUE TITLE
Map donuts: Consider adding white around the edge of the donut

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-components#345]
Suggestion - very open to critical feedback here!

The categorical colors in the donut are adjacent to the map background, which also has color. The adjacent colors can make the data colors (colors in the donut) more difficult to interpret. The suggestion is to add a small white border around the donut so that the data colors are separated from the map colors.

Example of data colors touching map colors:
<img width="546" alt="Screen Shot 2022-04-21 at 2 24 23 PM" src="https://user-images.githubusercontent.com/11710234/164529829-3e6e3d29-1da7-4da3-9bb7-5fd4a7f2216e.png">

**Comment by danicahelb** [comment]
SAM QA is paused for now
