### ISSUE TITLE
Map markers disappear at minimum zoom level

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-components#352]
When fully zoomed out, markers disappear in the map visualization (SCORE Seasonal, SCORE Mozambique, UMSP)

Presumably a problem with the longitude bounds being more than a "whole world" but will investigate.

**Comment by bobular** [comment]
I will 'up' the version level requirement for this repo at web-eda in one of my related tickets.

**Comment by danicahelb** [comment]
@aaronwlsong if something on the site is preventing you from QA'ing the ticket, you can put a pause label & note as to why QA is paused, but please leave the ticket in "ready for testing". thanks!

**Comment by aaronwlsong** [comment]
When I zoom out, looks like that the marker is there and the same as other studies. 

![Image](https://user-images.githubusercontent.com/61077845/173423470-5fe95413-6ce7-4801-a206-d27960eff981.png)


![Image](https://user-images.githubusercontent.com/61077845/173423918-8318764b-f22b-4b46-9a1f-88c0fc85088a.png)


![Image](https://user-images.githubusercontent.com/61077845/173423695-7333ad8d-8ee3-4bdb-bc0f-2fa5e68f914a.png)

**Comment by bobular** [comment]
This wasn't completely fixed.
