### ISSUE TITLE
Map viz in EDA freezes in Chrome (but this is likely a component issue)

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-components#360]
This is currently a live bug on clinepidb.org

The best way to reproduce it is with SCORE Mozambique in CHROME

No filters. Create a new map viz. Select "Age group" - let the map do its thing, then click the zoom out [-] button.  You may see that the spinner freezes and the browser locks up (and eventually asks if you want to kill it).

These warnings in the console may or may not be related.  I guess disabling screenshotting would be a good first experiment.

```
leaflet-simple-map-screenshoter.js:1 May be map size very big on that zoom level, we have error: RangeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': Out of memory at ImageData creation
```

In SCORE Seasonal, the same test will create clunky glitchy behaviour with browser lock-ups, but they resolve themselves.  
Also in SCORE Seasonal, the `Out of memory at ImageData creation` warnings do not appear.  May be a memory issue that SCORE Mozambique and Chrome exacerbate?

**Comment by bobular** [comment]
It's definitely screenshoter [sic] related because if you disable it, everything runs smoothly.

It was easy to replicate in my dev instance, but on qa today (thanks @dmfalke for rolling out changes) it seems smoother (but not perfect).  Maybe the overhead of running the development version is enough to tip the balance, and maybe that also happens on slower client hardware too.

**Comment by bobular** [comment]
Even in the dev environment, it seems snappier in Chrome today.  Not perfectly smooth, but not a showstopper like it was yesterday.

**Comment by bobular** [comment]
If I change the `setTimeout(0)` in thumbnails.ts to `setTimeout(5000)` and remove the "sleep 1000ms" in web-components/MapVEuMap.tsx it seems to be a lot smoother.

Because the return value from the Task.fromPromise() chain returns a cancel function, this timeout now acts like a debouncer, if I understand correctly.

We could pass the timeout duration as an arg to `useUpdateThumbnailEffect` so that it can be extended for maps and maybe scatterplots.  With a very long timeout, we would need to also trigger the thumbnail capture when the MapVisualization component unmounts (ideally only if an adequate thumbnail hasn't already been captured, in case it causes a slight delay for the user).

**Comment by SAK22** [comment]
Zoomed out, first zoom out click it did not freeze, second press of the - locked up the page

**Comment by SAK22** [comment]
Tried again and this time zooming out seems to work ok (tried this all on safari for a different browser)

**Comment by SAK22** [comment]
Tried on chrome, worked once. Tried again and worked for zooming out, zoomed back in and it froze and got a page is unresponsive message from chrome

**Comment by dmfalke** [comment]
There is definitely an issue with Chrome. It's related to generating a thumbnail for the "all viz" view. We may need to disable screenshots for maps in Chrome.

**Comment by SAK22** [comment]
Working now for me!
