### ISSUE TITLE
Map has a runtime exception when closing a visualisation (in EDA) within 1 second of zooming or panning

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-components#362]
Make a map viz in EDA. Pan the map a bit, then close it (or click "Visualize" tab) within 1 second of moving the map.

I can't seem to find a similar way to reproduce in Storybook.

I think this is due to an uncancelled debounced function `updateBounds` in SemanticMarkers.tsx

Should be easy enough to fix. Please take it if you fancy it. I will be doing another ticket first.

**Comment by jernestmyers** [comment]
Although on further inspection I'm now seeing there's sometimes a `TypeError` in the `SimpleMapScreenshoter`. It doesn't break the page at least, but not ideal.

![image](https://user-images.githubusercontent.com/69446567/173125931-69cff230-89bf-487b-8f2a-97cc6d7bc846.png)

**Comment by bobular** [comment]
Hi Jeremy,
I think actually rather than making `updateBounds` more fail-safe, we should try cancelling the debounced function.
(The debouncer internally does a timeout/sleep before calling the function, and we want to stop it doing that if the map has gone away.)

The function returned from useEffect's first argument function is a cleanup fn. We already have one, I think we just need to add something like below, but I haven't tested it.

```
return () => {
      map.off('resize dragend zoomend', debouncedUpdateBounds);
      // something like: debouncedUpdateBounds.cancel();
    };
```

**Comment by bobular** [comment]
I also wonder if instead of calling the regular `updateBounds()` before attaching the debounced version to the `map.on` event handler thingy, we should call the debounced version?  That means someone opening a map and immediately zooming, would benefit from the debouncing.  Possibly!

**Comment by bobular** [comment]
Hi @jernestmyers, do you have time for this today?
If not I can take it :smile:

**Comment by bobular** [comment]
No worries, I'm on it now.

**Comment by SAK22** [comment]
<img width="624" alt="Screenshot 2022-06-16 at 17 27 41" src="https://user-images.githubusercontent.com/22981342/174119863-b38b9839-e043-433c-bf78-9f2883d5cf0d.png">

I seem to get the pink spinner when trying to recreate this

**Comment by bobular** [comment]
Thanks Sarah, I've seen the spinner in one or two screenshots during my testing, but I don't know how to reproduce it. Do you have a failsafe method?

No "Sorry, something went wrong" popup errors, though, right?

**Comment by SAK22** [comment]
Now I cannot reproduce my spinner!

**Comment by bobular** [comment]
Actually I just got one, too, but I did kind of expect it, because that's what it looked like when I closed the map

![image](https://user-images.githubusercontent.com/308639/174127244-c09707dc-3aa0-424a-b1bc-8a914e638de8.png)
