### ISSUE TITLE
Expanded faceted plots only use top half of modal

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-components#373]
I'm not sure why this is the case.  Are we leaving a lot of space for long x-axis labels? Was it done on purpose?

I have tested this in Chrome and FF

Here's FF in a browser window at around 1000px height
![image](https://user-images.githubusercontent.com/308639/177615326-fffb100c-9248-4755-b298-34705a2d2709.png)

Aha, I see that in a smaller browser window (this time Chrome) it doesn't look so weird

![image](https://user-images.githubusercontent.com/308639/177615907-9f197dc5-a388-486a-ac1e-5b17fc80be46.png)

Two possible solutions:

Enlarge the plot, or decrease the size of the modal.

**Comment by danicahelb** [comment]
duplicates https://github.com/VEuPathDB/web-components/issues/339, so i am closing this ticket
