### ISSUE TITLE
Styling: Notification component aligns poorly in truncation warning

### ISSUE THREAD

**Issue by jernestmyers** [VEuPathDB/web-components#374]
The current notification for viz truncation has some alignment issues. The screenshot below shows the current styling. Notice how the button is not centered and how the icon gets rendered oddly by the wrapped text:

![image](https://user-images.githubusercontent.com/69446567/179285792-7e9f62cc-cabd-4594-9a03-db996d80501f.png)

I think the alignment looks broken and could be improved. I played with the styling in the dev tools and feel like these adjustments look better:

![image](https://user-images.githubusercontent.com/69446567/179286007-af499008-251b-49dc-8645-aef25a41efbf.png)

**Comment by asizemore** [comment]
I agree your update looks much better!

**Comment by aaronwlsong** [comment]
Looks good now, closing ticket. 

![Image](https://user-images.githubusercontent.com/61077845/195706424-9dbde4cd-c466-41ba-bfb6-140356a138d5.png)
