### ISSUE TITLE
AlphaFold visualization in Gene page

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/web-components#375]
https://redmine.apidb.org/issues/47707

kathryn is adding a new section in the gene page to visualize a protein structure as in:
https://embed.plnkr.co/plunk/WlRx73uuGA9EJbpn (only the first viz)

while we don't have the UI Kathryn will have the linkout available:
https://alphafold.ebi.ac.uk/entry/$uniprotId

dave and jamie slack (https://epvb.slack.com/archives/GBDR4LDNC/p1656522612596979):
-they have a web component: https://github.com/molstar/pdbe-molstar/wiki/2.-PDBe-Molstar-as-Web-component
-All of our new vizs are in https://github.com/VEuPathDB/web-components/.
-React docs mention re: using web components in a React app:
https://reactjs.org/docs/web-components.html#using-web-components-in-react
-In this particular instance, the web-component will be render outside of the typical react render phase (it will be done via dangerouslySetInnerHtml)

so... the plan is to create a new [web component](https://developer.mozilla.org/en-US/docs/Web/Web_Components) for this specific element and you would add a text attribute with some html with the specific data (just the uniprot id?)  in the tag attributes we define..

**Comment by dmfalke** [comment]
I don't think there is anything to do in this repo. The current plan is to directly use the web component that ebi publishes.
