### ISSUE TITLE
Yellow data truncation indicators can sometimes be extremely thin and hard to notice

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-components#378]
width of the yellow data truncation indicators are dependent on the range of the data. sometimes the width is so narrow that the yellow truncation bars are very hard to notice. See this example from MALED

<img width="633" alt="image" src="https://user-images.githubusercontent.com/25450900/180329990-ef1763c1-5a98-479a-b282-47bd61fc8633.png">

**Comment by dmfalke** [comment]
It appears the size of the truncation warning area is impacted by the log scale option.

**Comment by moontrip** [comment]
Just for a record, I have worked on this but I realized later that this was already addressed as a part of Bob's additional works with my original PRs, https://github.com/VEuPathDB/web-eda/pull/1241 & https://github.com/VEuPathDB/web-components/pull/371. 

Here is a screen capture of the above example with the PRs. They look good to me
![MAL-ED histogram](https://user-images.githubusercontent.com/12802305/182271238-5e503b1c-5ec8-46c7-9ed6-a466db3a8b48.png)

**Comment by bobular** [comment]
Sorry @moontrip

**Comment by SheenaTomko** [comment]
Yellow bars are now much more obvious on log scale
