### ISSUE TITLE
Long axis title truncated on barplot in Maps

### ISSUE THREAD

**Issue by sweverschulman** [VEuPathDB/web-components#386]
Long axis title was truncated on barplot in map visualization. 
It should read "181 Community repeated measures"

<img width="871" alt="Screen Shot 2022-08-16 at 2 34 58 PM" src="https://user-images.githubusercontent.com/62298921/184958204-8b84aa98-e29f-4879-9030-ab1d1d86ed1f.png">

**Comment by SheenaTomko** [comment]
Changed to only show the total count, entity type was removed. Looks good
