### ISSUE TITLE
Map: Zoom reset button for MapVEuMap

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-components#396]
For both FSM and map viz:

Add another Leaflet button in 'topleft' to reset the zoom to the "whole world". Functionality should be similar to the "globe" icon zoom reset button in the legacy map.

However, there is a complication in the new EDA world order...

MapVEuMap has `flyToMarkers` functionality, which on the EDA client side is usually triggered by the current center lat/long+zoom being equal to the default center and zoom.

So if the reset button zooms to the default map center/zoom, then the `flyTo` will be triggered and it will be confusing for users.

Do we just hack it and zoom to the center with one of the coordinates adjusted by 1e-08?

Slack discussion here: https://epvb.slack.com/archives/C03REHXRGBV/p1663066172525749

**Comment by bobular** [comment]
We could offer two buttons: zoom-to-data and zoom-to-world?

Any thoughts on icons?

**Comment by dmfalke** [comment]
I'm envisioning combining https://mui.com/material-ui/material-icons/?selected=CropFree and https://mui.com/material-ui/material-icons/?query=earth&selected=Public.

zoom-to-world would show the earth icon inside of the crop icon, and zoom-to-data would show the crop icon smaller than the earth icon (or maybe just some points inside the crop icon?).

These particular icons might be too busy, but maybe someone with some SVG design chops could make something interpretable?
