### ISSUE TITLE
Histogram: rename yAxisRange prop to dependentAxisRange and make it NumberRange type

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-components#61]
Has quite a few downstream consequences: e.g. `ChartMarkers`

Then in `ChartMarkers.stories.tsx` it's call yAxisRangeValue which could be renamed dependentAxisMaxValue or similar - or maybe pass a min/max range object rather than just the max to keep things consistent.

**Comment by bobular** [comment]
If we are going to be completely consistent about x and y being independent and dependent, there's an xAxisVariable in the data service API specs for histogram at least: https://veupathdb.github.io/EdaDataService/api.html#resources:/apps/pass/visualizations/numeric-histogram-bin-width:post 
This would need front+back end coordination if we decide to fix.
@d-callan

**Comment by bobular** [comment]
Sorry I missed this on the first review.

There's still `yAxisRange : [number, number]` in Histogram.tsx - this needs renaming please, to be consistent with the work done for #87

**Comment by bobular** [comment]
I had an idea about the empty subsections.

The subsection containers can be handled by a component that renders nothing when `children.length === 0` (or similar).

**Comment by moontrip** [comment]
This is made at #87 PR
