### ISSUE TITLE
Strange behavior when controlled input values are different from defaults in NumberAndDateRangeInputs.tsx

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-components#67]
This was discovered in the EDA Workspace setting. In that context, the range selection alternates between controlled and default.

More details are needed. Adding this issue just to keep track.

**Comment by bobular** [comment]
Probably related behaviour can be seen when selecting a range that includes the right-most edge in
https://veupathdb.github.io/web-components/?path=/story/plots-histogram--date-range-selection
