### ISSUE TITLE
Histogram: add "y-axis" controls

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-components#69]
via the usePlotControls mechanism, add controls for

- log scale on/off
- min/max range for axis
- absolute/relative

Ideally generalised for any axis, so two of these can be used for the x and y axis controls in a scatter plot.

For the first pass though, maybe just hard code it for the histogram y-axis

See also #61

**Comment by bobular** [comment]
Added the relative vs absolute control!  Nearly forgot this.

**Comment by moontrip** [comment]
@bobular and/or @dmfalke, I have a couple of questions regarding this task. First of all, it seems to me that the scope of the work is for adding UI controls, not actual functionality (e.g., changing plots) as the storybook does not have data (in the storybook) nor plot (plotly). Perhaps all I can check is whether a UI control that will be made changes its state correctly.

**Comment by dmfalke** [comment]
@moontrip That's correct about the scope of the work. You ought to be able to add stories to exhibit how these controls work.

These are the controls I think we want:

**independent (x) axis**
- Range

**dependent (y) axis**
- Range
- Log toggle
- Absolute vs relative

**Comment by moontrip** [comment]
@dmfalke thank your for your information. Can you please elaborate what the difference between independent and dependent axes is? Is it just for meaning a change with data (selection etc.)?

**Comment by dmfalke** [comment]
@moontrip a histogram shows the number of data points in a bin (range of values). For example, you can have a histogram of height. The independent axis would have the bins of height values (e.g., **1-2 feet**). The dependent axis would have the counts for each bin. Another way to think about it is, the **independent axis** represents the **domain**, and the **dependent axis** represents the **range**. The reason to use that terminology is that the user may change orientation, so x- and y-axis become ambiguous.

I also see you edited your earlier question, after I answered. I will try to clarify:
- **Range:** Adjusts the range of an axis. Should be a number/date range widget, as appropriate for the data. The dependent axis will also be a number range.
- **Log:** Toggles if the dependent axis values have a log-transform applied.
- **Absolute/relative:** Toggles if the dependent axis values are displayed as raw values or proportional to each other.

**Comment by moontrip** [comment]
@dmfalke thank you for your detailed explanation 👍
