### ISSUE TITLE
Strange behaviour when dragging x-axis of Histogram

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-components#75]
Sometimes it seems to really mess up the y-axis and then all you can see is truncated bars.

If you drag again it seems to correct itself.

It may be a Plotly bug, or we are not using it properly.

I'll take a screenshot next time I see it...

We should probably disable the dragging, since it doesn't play nicely with the server-side zooming that is planned.
see #70

**Comment by bobular** [comment]
I managed to reproduce it in FF on the feature site
https://feature.clinepidb.org/ce.feature/app/eda/DS_841a9f5259/2/variables/PCO_0000024/EUPATH_0000714

![image](https://user-images.githubusercontent.com/308639/113739556-d2a43f00-96f7-11eb-868d-d9cde775b90b.png)

It's quite reproducible - just slide the histogram to the right by about 100 units (drag on the x-axis)

Then I tried it in a FF private window.  That variable didn't show the bug, so I switched to another variable (Household->socio economic -> household wealth) and the buggy behaviour returned.

So maybe it only happens after switching between variables?

And I reproduced it in Chrome.  First variable is no problem, second exhibits the bug.

**Comment by dmfalke** [comment]
We should disable this, since it is only client side.

**Comment by bobular** [comment]
Also to do: add a prop to all plot components to enable/disable Plotly's mouse-over tooltips

**Comment by bobular** [comment]
Googled it

https://community.plotly.com/t/disable-pan-zoom-on-yaxis/9448

That's a CSS solution.

Looking for a config solution still...

**Comment by bobular** [comment]
https://plotly.com/javascript/reference/layout/yaxis/#layout-yaxis-fixedrange :-)
