### ISSUE TITLE
Controlled Sliders work but UX is terrible

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-components#81]
In `slider-no-debounce` branch - I had to remove the debouncing logic to make the sliders work (though I was not exactly sure how it was broken).

Fully controlled sliders work with debouncing applied directly to the getData() function (e.g. in HistogramViz `new-vis-histo` branch of web-eda), but there is zero feedback for the user until they have let go of the slider and the back end response has returned and updated the binWidth property.

The sliders need to show some feedback to the user before triggering on-change back up the component tree.

This may involve reimplementing some debouncing in the slider component?

Also - the display of the current value needs to be moved away from the slider handle.  It's unusuable at the moment.

**Comment by bobular** [comment]
I can imagine a possible solution being to maintain local state for the slider value in the slider component.  Then watch this value with useEffect to communicate new values upwards - perhaps with some debouncing built in?

**Comment by dmfalke** [comment]
I think local state is the ticket here. I would not include debouncing in the Slider. That should probably be left up to the consumer.

You can actually do this using the material-ui Slider component in its uncontrolled form. The trick is to pass in our component's `value` prop as a `key` prop to the material-ui Slider component. When a `key` prop value changes, React will effectively unmount the component, clearing out any associated state. This will cause the material-ui Slider to update when the incoming `value` prop changes, even though it is uncontrolled. This will allow our application code to debounce the change handler, but the Slider will remain responsive.

The relevant part of the component implementation might look like this:
```javascript
function Slider(props) {
  return (
    <Slider
      key={props.value}
      defaultValue={props.value}
      onChange={props.onChange}
      // ...
    />
  )
}
```

**Comment by dmfalke** [comment]
I'm planning to work on this asap.

**Comment by bobular** [comment]
Nice trick!

**Comment by dmfalke** [comment]
Turns out this trick doesn't give desired results. See linked PR.
